# Generated by Django 3.1.4 on 2021-11-03 17:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week_Plan',
            fields=[
                ('id', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tues'), (2, 'Wed'), (3, 'Thurs'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Interval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='Invalid length', message='Length has to be 4', regex='^.{4}$')])),
                ('end_time', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(code='Invalid length', message='Length has to be 4', regex='^.{4}$')])),
                ('time_diff', models.IntegerField()),
                ('task', models.TextField()),
                ('score', models.IntegerField()),
                ('status', models.BooleanField()),
                ('week_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ix', to='idealday.week_plan')),
            ],
        ),
    ]
