# Generated by Django 3.1.4 on 2021-11-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idealday', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='week_plan',
            name='id',
            field=models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thurs'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')], default=0, primary_key=True, serialize=False),
        ),
    ]
